git clone https://huggingface.co/spaces/PaddlePaddle/PaddleOCR
git clone https://huggingface.co/spaces/PaddlePaddle/paddlespeech
git clone https://huggingface.co/spaces/PaddlePaddle/wav2lip
git clone https://huggingface.co/spaces/PaddlePaddle/UIE-X
git clone https://huggingface.co/spaces/PaddlePaddle/ERNIE-ViLG
git clone https://huggingface.co/spaces/PaddlePaddle/deoldify
git clone https://huggingface.co/spaces/PaddlePaddle/ERNIE-Layout
git clone https://huggingface.co/spaces/PaddlePaddle/chinese-stable-diffusion
git clone https://huggingface.co/spaces/PaddlePaddle/PP-OCRv3-ch
git clone https://huggingface.co/spaces/PaddlePaddle/LSeg
git clone https://huggingface.co/spaces/PaddlePaddle/ERNIE-Zeus
git clone https://huggingface.co/spaces/PaddlePaddle/solov2
git clone https://huggingface.co/spaces/PaddlePaddle/transformer_zh-en
git clone https://huggingface.co/spaces/PaddlePaddle/jieba_paddle
git clone https://huggingface.co/spaces/PaddlePaddle/U2Net
git clone https://huggingface.co/spaces/PaddlePaddle/resnext101_32x16d_wsl
git clone https://huggingface.co/spaces/PaddlePaddle/se_hrnet64_imagenet_ssld
git clone https://huggingface.co/spaces/PaddlePaddle/se_resnext50_32x4d_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/darknet53_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/resnet_v2_101_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/resnet50_vd_10w
git clone https://huggingface.co/spaces/PaddlePaddle/mobilenet_v2_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/densenet161_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/dpn107_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/ghostnet_x1_3_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/hrnet30_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/se_resnext101_32x4d_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/animegan_v2_shinkai_53
git clone https://huggingface.co/spaces/PaddlePaddle/vgg13_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/fix_resnext101_32x48d_wsl_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/repvgg_b2g4_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/resnext101_vd_32x4d_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/mobilenet_v2_dishes
git clone https://huggingface.co/spaces/PaddlePaddle/resnet_v2_34_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/hrnet40_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/SnakeIdentification
git clone https://huggingface.co/spaces/PaddlePaddle/rexnet_2_0_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/pnasnet_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/resnet50_vd_dishes
git clone https://huggingface.co/spaces/PaddlePaddle/mobilenet_v2_imagenet_ssld
git clone https://huggingface.co/spaces/PaddlePaddle/efficientnetb1_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/efficientnetb0_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/resnext101_64x4d_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/resnext50_64x4d_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/rexnet_1_5_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/ghostnet_x1_3_imagenet_ssld
git clone https://huggingface.co/spaces/PaddlePaddle/resnext152_vd_32x4d_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/mobilenet_v3_large_imagenet_ssld
git clone https://huggingface.co/spaces/PaddlePaddle/food_classification
git clone https://huggingface.co/spaces/PaddlePaddle/resnet50_vd_animals
git clone https://huggingface.co/spaces/PaddlePaddle/resnet_v2_152_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/resnext152_32x4d_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/U2Net_Portrait
git clone https://huggingface.co/spaces/PaddlePaddle/UGATIT_92w
git clone https://huggingface.co/spaces/PaddlePaddle/UGATIT_83w
git clone https://huggingface.co/spaces/PaddlePaddle/UGATIT_100w
git clone https://huggingface.co/spaces/PaddlePaddle/repvgg_a0_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/repvgg_a1_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/SkyAR
git clone https://huggingface.co/spaces/PaddlePaddle/mobilenet_v2_animals
git clone https://huggingface.co/spaces/PaddlePaddle/pixel2style2pixel
git clone https://huggingface.co/spaces/PaddlePaddle/stgan_bald
git clone https://huggingface.co/spaces/PaddlePaddle/stylepro_artistic
git clone https://huggingface.co/spaces/PaddlePaddle/msgnet
git clone https://huggingface.co/spaces/PaddlePaddle/animegan_v2_shinkai_33
git clone https://huggingface.co/spaces/PaddlePaddle/animegan_v2_paprika_98
git clone https://huggingface.co/spaces/PaddlePaddle/animegan_v2_paprika_97
git clone https://huggingface.co/spaces/PaddlePaddle/animegan_v1_hayao_60
git clone https://huggingface.co/spaces/PaddlePaddle/animegan_v2_paprika_74
git clone https://huggingface.co/spaces/PaddlePaddle/animegan_v2_paprika_54
git clone https://huggingface.co/spaces/PaddlePaddle/animegan_v2_hayao_64
git clone https://huggingface.co/spaces/PaddlePaddle/animegan_v2_hayao_99
git clone https://huggingface.co/spaces/PaddlePaddle/pyramidbox_lite_mobile
git clone https://huggingface.co/spaces/PaddlePaddle/senta_bilstm
git clone https://huggingface.co/spaces/PaddlePaddle/lac
git clone https://huggingface.co/spaces/PaddlePaddle/MiDaS_Small
git clone https://huggingface.co/spaces/PaddlePaddle/MiDaS_Large
git clone https://huggingface.co/spaces/PaddlePaddle/chinese_ocr_db_crnn_mobile
git clone https://huggingface.co/spaces/PaddlePaddle/chinese_ocr_db_crnn_server
git clone https://huggingface.co/spaces/PaddlePaddle/photo2cartoon
git clone https://huggingface.co/spaces/PaddlePaddle/vgg19_imagenet
git clone https://huggingface.co/spaces/PaddlePaddle/U-GAT-IT-selfie2anime
